language: scala

scala:
  - 2.12.6

python:
  - 2.7

sudo: false

jdk:
  - oraclejdk8
  
services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.protobuf-2.6.1/src

install:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xzvf protobuf-2.6.1.tar.gz
  - pushd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install && popd

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates (https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  
jobs:  
  include:
    - stage: "Verify core and API modules"
      script: sbt ++$TRAVIS_SCALA_VERSION ";validate-api; validate-core"
      name: "Validate and verify API"
    - script: ./bin/func-test-api-travis.sh
      name: "Run API functional tests"
    - script: sbt ++$TRAVIS_SCALA_VERSION "validate-portal"
      name: "Validate portal"
    - script: ./bin/func-test-portal.sh
      name: "Run portal functional tests"
    - script: sbt ++$TRAVIS_SCALA_VERSION "verify"
      name: "Verify and run coverage on API and portal"

after_success:
  - bash <(curl -s https://codecov.io/bash)
