language: scala

scala:
  - 2.12.6

python:
  - 2.7

sudo: false

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass jekyll:3.2.1

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates (https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jobs:
  include:
    - name: "Validate and verify modules"
      script: sbt ++$TRAVIS_SCALA_VERSION ";validate; verify" && bash <(curl -s https://codecov.io/bash)
    - name: "Run API and portal functional tests"
      script: ./bin/func-test-portal.sh && ./bin/func-test-api-travis.sh
    - stage: Deploy
      name: "Deploy doc site"
      script: sbt ";project docs; publishMicrosite";
