language: scala

scala:
  - 2.12.7

python:
  - 2.7

sudo: false

jdk:
  - oraclejdk8
  - openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
  timeout: 900

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates (https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html)
  - sudo chown -R travis:travis $HOME/.sbt
  - sudo chown -R travis:travis $HOME/.ivy2/cache
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jobs:
  include:
    - name: "Validate and verify modules"
      script: sbt ++$TRAVIS_SCALA_VERSION ";validate; verify" && bash <(curl -s https://codecov.io/bash)
    - name: "Run API and portal functional tests"
      script: ./bin/func-test-portal.sh && ./bin/func-test-api-travis.sh
    - stage: Deploy
      if: branch = master AND type = push
      name: "Deploy doc site"
      script: sbt ";project docs; publishMicrosite";
