version: "3.0"
services:
  mysql:
    image: "mysql:5.7"
    env_file:
      .env
    container_name: "vinyldns-mysql"
    ports:
      - "19002:3306"

  dynamodb-local:
    image: "cnadiminti/dynamodb-local:2017-02-16"
    env_file:
      .env
    container_name: "vinyldns-dynamodb"
    ports:
      - "19000:8000"

  bind9:
    image: "vinyldns/bind9:0.0.4"
    env_file:
      .env
    container_name: "vinyldns-bind9"
    volumes:
      - ../bind9/etc:/var/cache/bind/config
      - ../bind9/zones:/var/cache/bind/zones
    ports:
      - "19001:53/tcp"
      - "19001:53/udp"

  elasticmq:
    image: s12v/elasticmq:0.13.8
    env_file:
      .env
    container_name: "vinyldns-elasticmq"
    ports:
      - "9324:9324"
    volumes:
      - ../elasticmq/custom.conf:/etc/elasticmq/elasticmq.conf

  # this file is copied into the target directory to get the jar!  won't run in place as is!
  api:
    build:
      context: ../build-api
    env_file:
      .env
    container_name: "vinyldns-api"
    ports:
      - "9000:9000"
    volumes:
      - ./docker.conf:/opt/docker/conf/application.conf
    depends_on:
      - mysql
      - bind9
      - elasticmq
      - dynamodb-local
