version: "3.0"
services:
  mysql-local:
    image: "mysql:5.7"
    environment:
    - MYSQL_ROOT_PASSWORD=pass # do not use quotes around the environment variables!!!
    - MYSQL_ROOT_HOST=% # this is required as mysql is currently locked down to localhost
    ports:
    - "19004:3306"
