version: "3.0"
services:
  mysql:
    image: "mysql:5.7"
    env_file:
      .env
    container_name: "vinyldns-mysql"
    ports:
      - "19002:3306"
    logging:
      driver: none

  bind9:
    image: "vinyldns/bind9:0.0.4"
    env_file:
      .env
    container_name: "vinyldns-bind9"
    volumes:
      - ./bind9/etc:/var/cache/bind/config
      - ./bind9/zones:/var/cache/bind/zones
    ports:
      - "19001:53/tcp"
      - "19001:53/udp"
    logging:
      driver: none

  localstack:
    image: localstack/localstack:0.10.4<skipPull>
    container_name: "vinyldns-localstack"
    ports:
      - "19000:19000"
      - "19006:19006"
      - "19007:19007"
    environment:
      - SERVICES=dynamodb:19000,sns:19006,sqs:19007
      - START_WEB=0

  # this file is copied into the target directory to get the jar!  won't run in place as is!
  api:
    build:
      context: api
    env_file:
      .env
    container_name: "vinyldns-api"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - bind9
      - localstack
    logging:
      driver: none

  functest:
    build:
      context: functest
    env_file:
      .env
    container_name: "vinyldns-functest"
    depends_on:
      - api
